# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_packages:
    - R6
    - assertthat
    - glue
    - hms
    - pkgcond
    - purrr
    - roxygen2
    - testextra

before_cache:
  - Rscript -e 'remotes::install_cran("pkgdown")'

before_script:
  - Rscript -e 'testextra::extract_tests()'
  - Rscript -e 'roxygen2::roxygenise(".", "rd")'

after_success:
  - Rscript -e 'covr::codecov()'

deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
